apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  labels:
    name: pv-for-log
 spec:
   accessMode:
   - ReadWriteMany
   capacity:
     storage: 1Gib
   hostPath:
     path: /pv/log
   ReclaimPolicy: Retain      


    
