apiVersion: v1
kind: Pod
metdata:
  name: webapp
spec:
  volumes:
  - name: data-log
    hostPath: 
      path: /var/log/webapp
      type: File
  containers:
  - name: webapp
    image: kodekloud/event-simulator
    volumeMounts:    
    - mountPath: /log
      name: data-log