apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  creationTimestamp: "2022-09-28T14:48:38Z"
  labels:
    run: pod
  name: pod
  namespace: default
  resourceVersion: "49439"
  uid: 6dd07eac-a243-4b8c-b6f5-57f84a5a1813
spec:
  containers:
  - args:
    - webapp
    image: kodekloud/simple-webapp-color
    imagePullPolicy: Always
    name: pod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ksdwl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-cluster1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-ksdwl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-09-28T14:48:38Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-09-28T14:48:38Z"
    message: 'containers with unready status: [pod]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-09-28T14:48:38Z"
    message: 'containers with unready status: [pod]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-09-28T14:48:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: kodekloud/simple-webapp-color
    imageID: ""
    lastState: {}
    name: pod
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "kodekloud/simple-webapp-color"
        reason: ImagePullBackOff
  hostIP: 192.168.49.2
  phase: Pending
  podIP: 10.244.0.17
  podIPs:
  - ip: 10.244.0.17
  qosClass: BestEffort
  startTime: "2022-09-28T14:48:38Z"
