apiVersion: v1
kind: Pod
metadata:
  name: logger
spec:
  containers:
  - image: nginx:alpine
    name: logger
    volumeMounts:
    - mounthPath: "/var/www/nginx"
      name: pod-volume
  volumes:
  - name: pod-volume
    persistentVolumeClaim:
      claimName: log-claim      