apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal-policy
spec:
  selector:
    matchLabels:
      name: internal
  policyTypes:
  - Ingress
  - Egress
  egres:
  - to:
    - podSelector:
        matchLabels: 
          name: payroll
      ports:
      - port: 8080
        protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          name: mysql
      ports:
      - port: 3306
        protocol: TCP          
