apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-app
  labels:
    app: httpd-lab
    type: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-lab
  template:
    metadata:
      name: httpd-pod
      labels:
        app: httpd-lab
    spec:
      containers:
      - name: httpd
        image: httpd:latest        