apiVersion: v1
kind: Pod
metadata:
  name: postgress-pod
  labels:
    name: postgres-pod
spec:
  containers:
    - name: postgres
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"