apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis
    app: demo-voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6479
  selector:
    name: redis-pod
    app: demo-voting-app
    
