apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    app: result
    type: webapp
spec:
  containers:
    - name: resultgapp
      image: docker.io/kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80