apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    app: voting
    type: webapp
spec:
  containers:
    - name: votingapp
      image: docker.io/kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80