apiVersion: v1
kind: Pod
metadata:
  name: worker-app
  labels:
    app: worker
    type: voting-webapp
spec:
  containers:
    - name: worker
      image: docker.io/kodekloud/examplevotingapp_worker:v1
