apiVersion: batch/v1
kind: CronJob
metadata:
  name: throw-dice-cron-job
spec:
  schedule: "30 21 * * *"
  jobTemplate:
    spec:
      comletions: 3
      parallelism: 3
      template:
       spec:
         containers:
         - name: throw
           image: kodekloud/throw-dice
              