apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBlinding
metadata:
  name: dev-user
subjects:
- kind: User
  name: dev-user
  apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io/v1